[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
sqlx = { version = "0.8.3", features = ["runtime-tokio", "postgres", "chrono"] }
